### PR TITLE
Typo corrections and comments

### PR DESCRIPTION
**Pull request by bakerdb**
1)  Corrected some typos.

2)  Deleted "(but note that requiring client authentication via mutual TLS may limit
interoperability of the client across server environments)."  I have several concerns about this phrase.  First, it tends to imply that a policy that requires a client to authenticate itself is bad policy -- which isn't necessarily the case, and who are we to tell organizations what their policy should be?  Second, maximizing the interoperability of a client is not the responsibility of an authorization server, or the organization holding the resource.  Third (related to 2), just because one authorization server requires a client to authenticate itself doesn't mean that every authorization server needs to do so.  

3) Deleted the question re 2.1.2, with my response --  I don’t think we should limit the applicability of our best practices to use-case 1-4 (patient/provider client access).  So I don’t see this as “hinting” at our cross-organizational approach.    As for detail, I tried not to duplicate the content in the OAuth spec on this model.  In what areas do you think more detail would be appropriate?

4) In 2.4.1, changed "To accomplish this" to "To fulfill this requirement" -- not clear what "this" referred to.

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks -- merged! For the mutual TLS comment, let's discuss separately (I likely didn't communicate what I meant very effectively in the parenthetical; happy to accept your removal of that for the moment.)

**Comment by whitehatguy** [comment]
Just happened to note this comment; wanted to just provide some informational background from my experiences with mutual TLS that might be interesting/useful tidbits for shaping the conversation.

First, TLS client authentication can be implemented in one of two ways from a TLS handshake perspective.  The first mode is that client authentication is requested upon initial handshake for any TLS connection to the server.  The second mode is that all TLS handshakes are accepted, and the sever accepts the HTTP request to evaluate if parameters are present (e.g. URI) that would require TLS client authentication, then challenges the client. 

Each of these methodologies has certain ramifications for an authorization server:

If the first methodology is used, it is possible for the browser to present a prompt for the user asking for certificate authentication.  This generally occurs if the user has a certificate installed locally for use with other services.  Since there is no general W3C governance over this mechanism, there's no guarantees what type of experience the user will encounter.  Often, this can be avoided by advertising a specific certificate issuer as part of the handshake.  This, however, assumes that the certificates being used for client authentication are centrally issued by a single authority.  The overall gist here is that an implementation would likely need to avoid commingling a single authorization URL for both user-facing authorization and TLS mutual authentication from client apps if using an approach that requests authentication on the initial handshake.

The second methodology is generally a bit more difficult for servers to implement, and is not as well supported by popular client libraries.  It does offer the benefit that a single authorization server URL could be utilized by both user agents, apps performing three-legged flows, and apps utilizing mutual TLS client credentials for two-legged flows.  The business logic requires a complex, tight coupling between the TLS handling and the authorization server:

- If the "/authorize" endpoint is being called by a user agent, present no TLS client credentials challenge.
- If the "/token" endpoint is being called with the grant type of "code", present no TLS client credentials challenge.
- If the "/token" endpoint is being called with the grant type of "client_credentials", then force a TLS renegotiation with a flag set to require client credentials.

Certain HTTPS client implementations that support TLS client authentication requests on the initial handshake may not have the capability of handling challenges sent in this manner.  These types of design considerations would need to be considered by an EHR developer, and perhaps have ramifications with respect to how services are deployed (e.g. separate FHIR endpoints that advertise a different authorization server specifically for TLS client credential-based authentication).

**Comment by bakerdb** [comment]
Thank you for offering this explanation, Matt.  

In my view, the first methodology would make no sense at all, since TLS is a transport-level protocol intended to secure a link between two software entities -- in this case, a client and a server.  TLS set-up should be imperceptible to the user (other than the lock icon).  

The second methodology is much more reasonable.  But I would agree that the lack of client libraries is an issue.  Another issue that I had not considered, but that others have pointed out in postings on this subject, is the fact that load balancers are often deployed in front of resource servers, and the load balancer will terminate the TLS link.  The Internet Draft

**Comment by bakerdb** [comment]
...(sorry, I wasn't finished) The Internet Draft on OAuth 2.0 security (https://tools.ietf.org/html/draft-tschofenig-oauth-security-00) suggests that in cases where end-to-end encryption from the client to a resource server is required, but a load balancer stands in the way, addition application-level encryption may be needed.  

I think the best treatment of this topic is the Oracle blog posting here -- https://blogs.oracle.com/OracleIDM/entry/follow_up_a_look_at  

All of this leads me to conclude that given the options to authenticate the client by client-secret (as we do for confidential clients in the app-authorization profile) or JWT Authentication Token (as we do for the organization-to-organization exchange profile), mutual TLS will rarely be needed.

**Comment by whitehatguy** [comment]
@bakerdb - your point on the load balancer is indeed valid - most of my implementations in the past have required specialized logic implemented within the terminating load balancer (e.g. iRules for F5 BIG-IP, specialized C code for Apache) that implement the business logic -- it's not something that generally works off-the-shelf.

**Pull request merged**
